// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA7295a6QJyAHpAj_VZQ9CGHc-O1yc9ts',
    appId: '1:839809408591:web:6c99ce71bd8425776b943a',
    messagingSenderId: '839809408591',
    projectId: 'music-player-ec3b9',
    authDomain: 'music-player-ec3b9.firebaseapp.com',
    storageBucket: 'music-player-ec3b9.firebasestorage.app',
    measurementId: 'G-KJSDFBLS0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnEyLcaxV4XjgOV397YHpzH3J70MLQweg',
    appId: '1:839809408591:android:1a4dc0709cc29d706b943a',
    messagingSenderId: '839809408591',
    projectId: 'music-player-ec3b9',
    storageBucket: 'music-player-ec3b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVYeBoTZPmOpv0XCVAZC3FurYEm7Q9Zbw',
    appId: '1:839809408591:ios:a89479ac68d369276b943a',
    messagingSenderId: '839809408591',
    projectId: 'music-player-ec3b9',
    storageBucket: 'music-player-ec3b9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVYeBoTZPmOpv0XCVAZC3FurYEm7Q9Zbw',
    appId: '1:839809408591:ios:a89479ac68d369276b943a',
    messagingSenderId: '839809408591',
    projectId: 'music-player-ec3b9',
    storageBucket: 'music-player-ec3b9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA7295a6QJyAHpAj_VZQ9CGHc-O1yc9ts',
    appId: '1:839809408591:web:f9ef9ab53c0b6f4a6b943a',
    messagingSenderId: '839809408591',
    projectId: 'music-player-ec3b9',
    authDomain: 'music-player-ec3b9.firebaseapp.com',
    storageBucket: 'music-player-ec3b9.firebasestorage.app',
    measurementId: 'G-CEDSF09DCY',
  );
}

